generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Proveedor
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          proveedor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        razon_social: {help: Nombre de la empresa o persona}
        cuit: {help: Número de CUIT sin guion '-'}
        telefono: {label: Teléfono., help: Se puede ingresar uno o varios números de teléfonos}
        condicionfiscal_id: {label: Cond. Fiscal}
        localidad_id: {label: Ciudad}
      list:
        table_method: retrieveConJoins
        title: Administraci&oacute;n de Proveedores
        display: [cuit, razon_social, _ciudad, telefono, email]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
      filter:  ~
      form:    ~
      edit:
        title: Modificar Proveedor
      new:
        title: Nuevo Proveedor