generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CursoInscripcion
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          curso_inscripcion
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
        tipo_insc_id: {label: Tipo Inscripcion}
      list:
        title: Insacriptos a Cursos
        display: [Curso, nombre, correo, fecha, TipoInscripcion]
        actions:
          _new: ~
          imprimir: ~
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [curso_id, cliente_id, nombre, correo, fecha, tipo_insc_id]                
      form:    ~
      edit:
        title: Editar Inscripcion
        display: [curso_id, cliente_id, nombre, correo, fecha, tipo_insc_id, comentario]        
      new:
        title: Nueva Inscripcion
        display: [curso_id, cliente_id, nombre, correo, fecha, tipo_insc_id, comentario]