generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Cuenta
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cuenta
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Cuentas para Compras
        display: [nombre]
        object_actions:
          _delete: ~
          _edit: ~
      filter:  ~
      form:    ~
      edit:
        title: Modificar Cuenta
      new:
        title: Nueva Cuenta
