compra2:
  class: sfDoctrineRouteCollection
  options:
    model:                Compra2
    module:               compras
    prefix_path:          /compras
    column:               id
    with_wildcard_routes: true

traza2:
  class: sfDoctrineRouteCollection
  options:
    model:                Traza2
    module:               trazaprod
    prefix_path:          /trazaprod
    column:               id
    with_wildcard_routes: true

producto2:
  class: sfDoctrineRouteCollection
  options:
    model:                Producto2
    module:               productos
    prefix_path:          /productos
    column:               id
    with_wildcard_routes: true

grupoprod2:
  class: sfDoctrineRouteCollection
  options:
    model:                Grupoprod2
    module:               prodgrupo
    prefix_path:          /prodgrupo
    column:               id
    with_wildcard_routes: true

curso_mail_enviado:
  class: sfDoctrineRouteCollection
  options:
    model:                CursoMailEnviado
    module:               cursmail
    prefix_path:          /cursmail
    column:               id
    with_wildcard_routes: true

curso_inscripcion:
  class: sfDoctrineRouteCollection
  options:
    model:                CursoInscripcion
    module:               insccurso
    prefix_path:          /insccurso
    column:               id
    with_wildcard_routes: true

curso_inscripcion_curasis:
  class: sfDoctrineRouteCollection
  options:
    model:                CursoInscripcion
    module:               curasis
    prefix_path:          /curasis
    column:               id
    with_wildcard_routes: true

curso:
  class: sfDoctrineRouteCollection
  options:
    model:                Curso
    module:               curso
    prefix_path:          /curso
    column:               id
    with_wildcard_routes: true

cliente_seguimiento:
  class: sfDoctrineRouteCollection
  options:
    model:                ClienteSeguimiento
    module:               cliseg
    prefix_path:          /cliseg
    column:               id
    with_wildcard_routes: true
    
detalle_resumen_ultcompdet:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleResumen
    module:               ultcompdet
    prefix_path:          /ultcompdet
    column:               id
    with_wildcard_routes: true

detalle_resumen_detultcomp:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleResumen
    module:               detultcomp
    prefix_path:          /detultcomp
    column:               id
    with_wildcard_routes: true

control_stock:
  class: sfDoctrineRouteCollection
  options:
    model:                ControlStock
    module:               ctrlstock
    prefix_path:          /ctrlstock
    column:               id
    with_wildcard_routes: true

listado_compras:
  class: sfDoctrineRouteCollection
  options:
    model:                ListadoCompras
    module:               listcomp
    prefix_path:          /listcomp
    column:               id
    with_wildcard_routes: true

cliente_ultima_compra:
  class: sfDoctrineRouteCollection
  options:
    model:                ClienteUltimaCompra
    module:               ultcomp
    prefix_path:          /ultcomp
    column:               id
    with_wildcard_routes: true

lote:
  class: sfDoctrineRouteCollection
  options:
    model:                Lote
    module:               lote
    prefix_path:          /lote
    column:               id
    with_wildcard_routes: true

admin_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               adminuser
    prefix_path:          /adminuser
    column:               id
    with_wildcard_routes: true

producto_traza:
  class: sfDoctrineRouteCollection
  options:
    model:                ProductoTraza
    module:               traza
    prefix_path:          /traza
    column:               id
    with_wildcard_routes: true

pedido_pedcerr:
  class: sfDoctrineRouteCollection
  options:
    model:                Pedido
    module:               pedcerr
    prefix_path:          /pedcerr
    column:               id
    with_wildcard_routes: true

pedido_pedvend:
  class: sfDoctrineRouteCollection
  options:
    model:                Pedido
    module:               pedvend
    prefix_path:          /pedvend
    column:               id
    with_wildcard_routes: true

detalle_pedido_detpedidos:
  class: sfDoctrineRouteCollection
  options:
    model:                DetallePedido
    module:               detpedidos
    prefix_path:          /detpedidos
    column:               id
    with_wildcard_routes: true

pedido_pedidos:
  class: sfDoctrineRouteCollection
  options:
    model:                Pedido
    module:               pedidos
    prefix_path:          /pedidos
    column:               id
    with_wildcard_routes: true

nuevo_pedido:
  url: /detped
  param: { module: detped, action nuevo}
  
detalle_pedido:
  class: sfDoctrineRouteCollection
  options:
    model:                DetallePedido
    module:               detped
    prefix_path:          /detped
    column:               id
    with_wildcard_routes: true

pedido:
  class: sfDoctrineRouteCollection
  options:
    model:                Pedido
    module:               ped
    prefix_path:          /ped
    column:               id
    with_wildcard_routes: true

autocomplete:
  url: /autocomplete
  param: { module: cli, action autocomplete}

comp_fact:
  class: sfDoctrineRouteCollection
  options:
    model:                CompFact
    module:               listfcomp
    prefix_path:          /listfcomp
    column:               id
    with_wildcard_routes: true

vta_fact:
  class: sfDoctrineRouteCollection
  options:
    model:                VtaFact
    module:               listfvta
    prefix_path:          /listfvta
    column:               id
    with_wildcard_routes: true
    
cta_cte_prov:
  class: sfDoctrineRouteCollection
  options:
    model:                CtaCteProv
    module:               ctaprov
    prefix_path:          /ctaprov
    column:               id
    with_wildcard_routes: true

detalle_presupuesto:
  class: sfDoctrineRouteCollection
  options:
    model:                DetallePresupuesto
    module:               detpresu
    prefix_path:          /detpresu
    column:               id
    with_wildcard_routes: true

presupuesto:
  class: sfDoctrineRouteCollection
  options:
    model:                Presupuesto
    module:               presu
    prefix_path:          /presu
    column:               id
    with_wildcard_routes: true

dev_producto:
  class: sfDoctrineRouteCollection
  options:
    model:                DevProducto
    module:               devprod
    prefix_path:          /devprod
    column:               id
    with_wildcard_routes: true

detalle_resumen_devprod:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleResumen
    module:               devprod
    prefix_path:          /devprod
    column:               id
    with_wildcard_routes: true

listado_cobros:
  class: sfDoctrineRouteCollection
  options:
    model:                ListadoCobros
    module:               listcob
    prefix_path:          /listcob
    column:               id
    with_wildcard_routes: true

cliente_saldos:
  class: sfDoctrineRouteCollection
  options:
    model:                Cliente
    module:               saldos
    prefix_path:          /saldos
    column:               id
    with_wildcard_routes: true

tipo_moneda:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoMoneda
    module:               moneda
    prefix_path:          /moneda
    column:               id
    with_wildcard_routes: true

producto_inicio:
  class: sfDoctrineRouteCollection
  options:
    model:                Producto
    module:               inicio
    prefix_path:          /inicio
    column:               id
    with_wildcard_routes: true

listado_ventas:
  class: sfDoctrineRouteCollection
  options:
    model:                ListadoVentas
    module:               listvta
    prefix_path:          /listvta
    column:               id
    with_wildcard_routes: true

tipo_factura:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoFactura
    module:               tipfct
    prefix_path:          /tipfct
    column:               id
    with_wildcard_routes: true

cuenta:
  class: sfDoctrineRouteCollection
  options:
    model:                Cuenta
    module:               cta
    prefix_path:          /cta
    column:               id
    with_wildcard_routes: true

det_lis_precio:
  class: sfDoctrineRouteCollection
  options:
    model:                DetLisPrecio
    module:               detlis
    prefix_path:          /detlis
    with_wildcard_routes: true

lista_precio:
  class: sfDoctrineRouteCollection
  options:
    model:                ListaPrecio
    module:               lista
    prefix_path:          /lista
    column:               id
    with_wildcard_routes: true

tipo_cliente:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoCliente
    module:               tipcli
    prefix_path:          /tipcli
    column:               id
    with_wildcard_routes: true

ctacte:
  class: sfDoctrineRouteCollection
  options:
    model:                CtaCte
    module:               ctacte
    prefix_path:          /ctacte
    column:               id
    with_wildcard_routes: true

det_fact_compra:
  class: sfDoctrineRouteCollection
  options:
    model:                DetFactCompra
    module:               detfctcomp
    prefix_path:          /detfctcomp
    column:               id
    with_wildcard_routes: true

fact_compra:
  class: sfDoctrineRouteCollection
  options:
    model:                FactCompra
    module:               fctcomp
    prefix_path:          /fctcomp
    column:               id
    with_wildcard_routes: true

pago:
  class: sfDoctrineRouteCollection
  options:
    model:                Pago
    module:               pago
    prefix_path:          /pago
    column:               id
    with_wildcard_routes: true

banco:
  class: sfDoctrineRouteCollection
  options:
    model:                Banco
    module:               banco
    prefix_path:          /banco
    column:               id
    with_wildcard_routes: true

tipo_cobro_pago:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoCobroPago
    module:               tipcobpag
    prefix_path:          /tipcobpag
    column:               id
    with_wildcard_routes: true

detalle_compra:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleCompra
    module:               detcomp
    prefix_path:          /detcomp
    column:               /:compra_id/:producto_id
    with_wildcard_routes: true

compra:
  class: sfDoctrineRouteCollection
  options:
    model:                Compra
    module:               compra
    prefix_path:          /compra
    column:               id
    with_wildcard_routes: true

stock:
  class: sfDoctrineRouteCollection
  options:
    model:                Producto
    module:               stock
    prefix_path:          /stock
    column:               id
    with_wildcard_routes: true

cobro:
  class: sfDoctrineRouteCollection
  options:
    model:                Cobro
    module:               cobro
    prefix_path:          /cobro
    column:               id
    with_wildcard_routes: true

detalle_venta:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleVenta
    module:               detvta
    prefix_path:          /detvta
    column:               venta_id/producto_id
    with_wildcard_routes: true

venta:
  class: sfDoctrineRouteCollection
  options:
    model:                Venta
    module:               vta
    prefix_path:          /vta
    column:               id
    with_wildcard_routes: true

condicion_fiscal:
  class: sfDoctrineRouteCollection
  options:
    model:                CondicionFiscal
    module:               condfiscal
    prefix_path:          /condfiscal
    column:               id
    with_wildcard_routes: true

detalle_resumen:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleResumen
    module:               detres
    prefix_path:          /detres
    column:               id
    with_wildcard_routes: true

resumen:
  class: sfDoctrineRouteCollection
  options:
    model:                Resumen
    module:               resumen
    prefix_path:          /resumen
    column:               id
    with_wildcard_routes: true

proveedor:
  class: sfDoctrineRouteCollection
  options:
    model:                Proveedor
    module:               prov
    prefix_path:          /prov
    column:               id
    with_wildcard_routes: true

producto:
  class: sfDoctrineRouteCollection
  options:
    model:                Producto
    module:               prod
    prefix_path:          /prod
    column:               id
    with_wildcard_routes: true

grupoprod:
  class: sfDoctrineRouteCollection
  options:
    model:                Grupoprod
    module:               grupoprod
    prefix_path:          /grupoprod
    column:               id
    with_wildcard_routes: true

localidad_loc:
  class: sfDoctrineRouteCollection
  options:
    model:                Localidad
    module:               loc
    prefix_path:          /loc
    column:               id
    with_wildcard_routes: true

localidad:
  class: sfDoctrineRouteCollection
  options:
    model:                localidad
    module:               loc
    prefix_path:          /loc
    column:               id
    with_wildcard_routes: true

provincia:
  class: sfDoctrineRouteCollection
  options:
    model:                Provincia
    module:               provincia
    prefix_path:          /provincia
    column:               id
    with_wildcard_routes: true

cliente:
  class: sfDoctrineRouteCollection
  options:
    model:                Cliente
    module:               cli
    prefix_path:          /cli
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: inicio, action: index }

backup:
  url:   /backup
  param: { module: admins, action: index }  

log:
  url:   /log
  param: { module: admins, action: log }  

Triggers:
  url:   /triggers
  param: { module: admins, action: triggers }  

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  prefix_path: /:sf_culture

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }