generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Resumen
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          resumen
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id:    { label: Numero }
        fecha: { date_format: dd/MM/yyyy }
        lista_id: { label: Lista Precio }
        nro_factura: { label: Numero, help: En caso de generar las factura desde afip cargar el numero en forma manual }
        tipofactura_id: { label: Factura }
        tipo_venta_id: { label: Tipo Venta }
        afip_estado: { label: AFIP }
        pto_vta: { label: Punto de Venta, help: El punto 4 es para facturas generadas en afip y el punto 5 es para las facturas generadas por sistema}
      list:
        max_per_page: 10
        table_method: retrieveConJoins
        title: Ventas realizadas
        display: [_factura, fecha, TipoVenta,Cliente, _remito, _afip_estado]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
          detalle: {label: Detalle}
          mail: {label: Email}
          factura: {label: Enviar AFIP}
        batch_actions:
          _delete: {label: Eliminar}
      filter:
        display: [tipofactura_id, tipo_venta_id, fecha, cliente_id, remito_id, nro_factura]
      form:
        display: [fecha, cliente_id, tipofactura_id, pto_vta, nro_factura, tipo_venta_id, cuit, afip, saldo_pesos, saldo_dolar, observacion]
        actions:
          _list: {label: Volver}
          _save: {label: 'Guardar y Agregar Detalle'}
      edit:
        title: Modificar Venta
      new:
        title: Nueva Venta
