generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DetalleResumen
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          detalle_resumen
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        precio: {label: Precio Unitario, help: Muestra automáticamente el precio de venta del producto o lo calcula según la lista de precio seleccionada en la venta}
        bonificados: {help: Cantidad productos bonificados aparte de la cantidad vendida.}
        det_remito_id: {label: Remito, help: Dejar vacio si no corresponde a un remito}
      list:
        table_method: retrieveConJoins
        title: Detalle de la Venta
        max_per_page: 999
        display: [_producto, nro_lote, _precio, cantidad, tipo_descuento, _descuento, sub_total, iva, _total, observacion]
        object_actions:
          _delete: ~
        batch_actions: {}
        actions:
          _new: ~
          imprimir: {label: Imprimir}
          recalcular: {label: Recalcular Precio}
      filter: ~
      form: ~
      edit:
        title: Modificar Detalle
      new:
        title: Nuevo Detalle
        display: [producto_id, nro_lote, det_remito_id, precio, cantidad, sub_total, tipo_descuento, descuento, iva, total, observacion]