generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Pago
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pago
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
      list:
        title: Pagos a Proveedores
        display: [Proveedor, fecha, monto, Tipo, Banco, numero, observacion]
        object_actions:
          _delete: ~
          _edit: ~
      filter:  ~
      form:    ~
      edit:
        title: Modificar Pago a Proveedor
      new:
        title: Nuevo Pago a Proveedor
