generator:
  class: sfDoctrineGenerator
  param:
    model_class:           VentasZona
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ventas_zona
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { label: Fecha de Venta, date_format: dd/MM/yyyy }
        fecha_cobrado: { label: Fecha de cobro de la factura, date_format: dd/MM/yyyy }
        pagado: { label: Comision Pagada }
        cobrado: { label: Factura Cobrada Completa }
        grupoprod_id: { label: Grupo del producto }
      list:
        max_per_page: 9999
        table_method: retrieveConJoins
        title: Ventas por Zona
        display: [fecha, Resumen, Zona, Cliente, Producto, _precio, _cantidad, _neto, _iva, _total, cobrado, fecha_cobrado, pagado]
        object_actions: []
        batch_actions:
           pagar: ~
        actions:
          excel: ~
      filter:
        display: [fecha, cliente_id, grupoprod_id, producto_id, nro_lote, zona_id, cobrado, fecha_cobrado, pagado]
      form:    ~
      edit:    ~
      new:     ~
