generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Provincia
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          provincia
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Administraci&oacute;n de Provincias
        display: [nombre]
        object_actions:
          _delete: ~
          _edit: ~
      filter:  ~
      form:    ~
      edit:
        title: Modificar Provincia
      new:
        title: Nueva Provincia
