generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DevProducto
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          dev_producto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
        Resumen: {label: Venta}
        resumen_id: {label: Venta}
        sfGuardUser: {label: Usuario}
        cae_afip: {label: AFIP}
        cantidad: {label: Cant}
        nro_lote: {label: Lote}
      list:
        table_method: retrieveConJoins
        title: Productos Devueltos
        display: [Zona, fecha, _comprobante, Cliente, Producto, nro_lote, cantidad, _precio, _iva, _total, _cae_afip]
        actions:
          _new: {label: Nuevo}
          imprimir_pagina: {label: Imprimir Pagina}
          excel_pagina: {label: Descargar Pagina}
          excel_todo: {label: Descargar Todo}
        object_actions:
          _delete: {label: Eliminar}
          asociada: {label: Ver Fact}
          factura: {label: Enviar AFIP}
          comprobante_imp: {label: Imprimir}
          mail: {label: Enviar Mail}
      filter:
        display: [fecha, cliente_id, producto_id, nro_lote]
      form:    ~
      edit:    ~
      new:
        title: Devolver Producto
        display: [fecha, cliente_id, producto_id, resumen_id, nro_lote, cantidad, precio, iva, total, precio_unitario, iva_unitario, observacion]
      show:
        display: [fecha, _comprobante, Cliente, Producto, nro_lote, cantidad, _precio, _iva, _total]