generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PagoComision
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pago_comision
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
      list:
        title: Pago de Comisiones
        display: [fecha, Revendedor, _monto, Tipo, Banco, referencia, observacion]
        actions: []
        object_actions:
            _delete: ~
            _edit: ~
            imprimir: ~
            mail: ~
        batch_actions: []            
      filter:  ~
      form:    ~
      edit:
        title: Completar informacion del pago a %%Revendedor%%
        display: [fecha, monto, moneda_id, monto, tipo_id, banco_id, referencia, observacion]
      new:     ~
