generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CondicionFiscal
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          condicion_fiscal
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Condiciones Fiscales
        display: [nombre]
        object_actions:
          _delete: ~
          _edit: ~
      filter:  ~
      form:    ~
      edit:
        title: Modificar Condici&oacute;n Fiscal
      new:
        title: Nueva Condici&oacute;n Fiscal
