generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          admin_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        is_active: { label: Activo }
        is_super_admin: { label: Es Administrador    }
        username: { label: Usuario }
        first_name: { label: Nombres }
        last_name: { label: Apellido }
        password: { label: Clave }
        password_again: { label: Confirmar Clave }
        email_address: { label: Email }
        zona_id: { label: Zona donde puede vender}
        usuario_zona: { label: Zonas que puede ver en los listados}
        permissions_list: { label: Opciones de menu que puede ver}
      list:
        title: Usuarios
        display: [is_active, Zona, username, =last_name, first_name, es_cliente]
        object_actions:
            _edit: {label: Modificar}
            _delete: {label: Eliminar}
      form:
        class: sfGuardUserAdminForm
        display: [first_name, last_name, email_address, username, password, password_again, is_super_admin, is_active, es_cliente, zona_id, usuario_zona, permissions_list]
      filter:
        display: [is_active, zona_id, username, first_name, last_name, es_cliente]
      edit:
        title: Editrar Usuario "%%first_name%% %%last_name%%"
      new:
